// import 'commande.dart';
// import 'etat.dart';
// import 'medicament.dart';
//
// List<Commande> commands = [
//   Commande(
//     id: 'Command1',
//     idPharamcie: 'Pharmacie1',
//     idClient: 'Client1',
//     etat: Etat.EnPreparartion,
//     medicaments: [
//       Medicament(
//         id: 'Medicament1',
//         nomMedicament: 'Paracetamol',
//         prix: '5.0',
//         remise: '0.5',
//         image: 'paracetamol.jpg',
//         quantite: 50,
//         detail: 'Fever reducer',
//         idPharmacie: 'Pharmacie1',
//         nomCategorie: 'Painkillers',
//         idPromotion: 'Promo1',
//         seuil: 10,
//         AlerteForSeuil: 5,
//         tracabilite: 'Trace1',
//       ),
//       Medicament(
//         id: 'Medicament2',
//         nomMedicament: 'Ibuprofen',
//         prix: '8.0',
//         remise: '1.0',
//         image: 'ibuprofen.jpg',
//         quantite: 30,
//         detail: 'Anti-inflammatory',
//         idPharmacie: 'Pharmacie1',
//         nomCategorie: 'Painkillers',
//         idPromotion: 'Promo2',
//         seuil: 15,
//         AlerteForSeuil: 8,
//         tracabilite: 'Trace2',
//       ),
//       Medicament(
//         id: 'Medicament3',
//         nomMedicament: 'Aspirin',
//         prix: '4.0',
//         remise: '0.3',
//         image: 'aspirin.jpg',
//         quantite: 40,
//         detail: 'Blood thinner',
//         idPharmacie: 'Pharmacie1',
//         nomCategorie: 'Painkillers',
//         idPromotion: 'Promo3',
//         seuil: 12,
//         AlerteForSeuil: 6,
//         tracabilite: 'Trace3',
//       ),
//     ],
//   ),
//   Commande(
//     id: 'Command2',
//     idPharamcie: 'Pharmacie2',
//     idClient: 'Client2',
//     etat: Etat.EnCoursLivraison,
//     medicaments: [
//       Medicament(
//         id: 'Medicament4',
//         nomMedicament: 'Antibiotic',
//         prix: '15.0',
//         remise: '2.0',
//         image: 'antibiotic.jpg',
//         quantite: 25,
//         detail: 'Infection treatment',
//         idPharmacie: 'Pharmacie2',
//         nomCategorie: 'Antibiotics',
//         idPromotion: 'Promo4',
//         seuil: 8,
//         AlerteForSeuil: 4,
//         tracabilite: 'Trace4',
//       ),
//       Medicament(
//         id: 'Medicament5',
//         nomMedicament: 'Cough Syrup',
//         prix: '7.0',
//         remise: '0.8',
//         image: 'cough_syrup.jpg',
//         quantite: 35,
//         detail: 'Relief for cough',
//         idPharmacie: 'Pharmacie2',
//         nomCategorie: 'Cough and Cold',
//         idPromotion: 'Promo5',
//         seuil: 20,
//         AlerteForSeuil: 10,
//         tracabilite: 'Trace5',
//       ),
//       Medicament(
//         id: 'Medicament6',
//         nomMedicament: 'Pain Relief Gel',
//         prix: '12.0',
//         remise: '1.5',
//         image: 'pain_relief_gel.jpg',
//         quantite: 15,
//         detail: 'Topical pain relief',
//         idPharmacie: 'Pharmacie2',
//         nomCategorie: 'Pain Relief',
//         idPromotion: 'Promo6',
//         seuil: 10,
//         AlerteForSeuil: 5,
//         tracabilite: 'Trace6',
//       ),
//     ],
//   ),
//   Commande(
//     id: 'Command3',
//     idPharamcie: 'Pharmacie3',
//     idClient: 'Client3',
//     etat: Etat.Livraison,
//     medicaments: [
//       Medicament(
//         id: 'Medicament7',
//         nomMedicament: 'Vitamin C',
//         prix: '3.0',
//         remise: '0.2',
//         image: 'vitamin_c.jpg',
//         quantite: 60,
//         detail: 'Boosts immune system',
//         idPharmacie: 'Pharmacie3',
//         nomCategorie: 'Vitamins',
//         idPromotion: 'Promo7',
//         seuil: 25,
//         AlerteForSeuil: 12,
//         tracabilite: 'Trace7',
//       ),
//       Medicament(
//         id: 'Medicament8',
//         nomMedicament: 'Allergy Medication',
//         prix: '10.0',
//         remise: '1.0',
//         image: 'allergy_medication.jpg',
//         quantite: 20,
//         detail: 'Relief for allergies',
//         idPharmacie: 'Pharmacie3',
//         nomCategorie: 'Allergy Relief',
//         idPromotion: 'Promo8',
//         seuil: 15,
//         AlerteForSeuil: 7,
//         tracabilite: 'Trace8',
//       ),
//       Medicament(
//         id: 'Medicament9',
//         nomMedicament: 'Eye Drops',
//         prix: '6.0',
//         remise: '0.5',
//         image: 'eye_drops.jpg',
//         quantite: 30,
//         detail: 'For dry eyes',
//         idPharmacie: 'Pharmacie3',
//         nomCategorie: 'Eye Care',
//         idPromotion: 'Promo9',
//         seuil: 18,
//         AlerteForSeuil: 9,
//         tracabilite: 'Trace9',
//       ),
//     ],
//   ),
// ];